TELEGRAM_BOT_TOKEN = "replace_with_your_token"
TELEGRAM_CHAT_ID = "replace_with_your_chat_id"
ALPACA_API_KEY = "replace_with_your_alpaca_api_key"
ALPACA_SECRET_KEY = "replace_with_your_alpaca_secret_key"